spring:
  data:
    mongodb:
      uri: mongodb+srv://aadeshsrivastava48:JoSHlRjGpOB7pM68@cluster0.fvhmh72.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  profiles:
    active: prod

  mail:
    host: smtp.gmail.com
    port: 587
    username: krazyyai@gmail.com
    password: huvg gwho ouan xozl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: localhost
    port: 6379

genai:
  api:
    url: https://genaiapp-wywr.onrender.com/analyze-journals
    key: supersecret123
