spring:
  profiles:
    active: prod

  mail:
    host: smtp.gmail.com
    port: 587
    username: krazyyai@gmail.com
    password: huvg gwho ouan xozl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
